language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

branches:
  only:
  - migration/TypeScript 
  - /^release-.*/


install:
  - npm uninstall typescript --no-save
  - npm install

cache:
  directories:
    - node_modules

git:
  depth: 1